

# This file was *autogenerated* from the file full_adder.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2000 = Integer(2000); _sage_const_160 = Integer(160); _sage_const_15 = Integer(15); _sage_const_0 = Integer(0)
load('DGHV.sage')

gamma, eta, rho = _sage_const_2000 , _sage_const_160 , _sage_const_15 
dghv = DGHV(gamma, eta, rho)

def full_adder(dghv, bit_a, bit_b, carry):
    ca = dghv.enc(bit_a)
    cb = dghv.enc(bit_b)
    carryenc = dghv.enc(carry)

    # Sum the numberes
    axorb = dghv.add(ca, cb)
    soma = dghv.add(axorb, carryenc)

    # Carry out of the sum
    # Carryout = (A AND B) XOR (Carryin AND (A XOR B))
    a_and_b = dghv.mult(ca, cb)
    carry_and_axorb = dghv.mult(carryenc, axorb)
    carry_out = dghv.add(a_and_b, carry_and_axorb)
    return soma, carry_out

s, cout = full_adder(dghv, _sage_const_0 , _sage_const_0 , _sage_const_0 )
print(f"The sum is {dghv.dec(s)}, with a CarryOut = {dghv.dec(cout)}")

